import { createApp } from 'vue';
import { createPinia } from 'pinia';
// import FrontLayout from '@/js/layouts/FrontLayout.vue';
import App from '@/js/App.vue';
import router from '@/js/router';
import '@/scss/main.scss';
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount('#app');
